### PR TITLE
fix(blackman windowing): allow odd-length windows

### LINKED ISSUE #264: Blackman Window broken for odd length buffers
Here's a [demo]. Not exactly a huge problem in Meyda because we enforce a power of 2 buffer size. Still something we should fix.

[demo]: https://runkit.com/raw/windowing-functions-in-meyda

### PR DESCRIPTION
**Pull request by hughrawlinson**
fix #264

### CODE REVIEW

File: src/windowing.js [hunk 1]
```diff
@@ -1,17 +1,17 @@
...
   for (let i = 0; i < size / 2; i++) {
-    blackmanBuffer[i] = 0.42 - 0.5 * Math.cos(i * coeff1) +
-            0.08 * Math.cos(i * coeff2);
+    blackmanBuffer[i] =
+      0.42 - 0.5 * Math.cos(i * coeff1) + 0.08 * Math.cos(i * coeff2);
   }
 
   //second half of the window
-  for (let i = size / 2; i > 0; i--) {
+  for (let i = Math.ceil(size / 2); i > 0; i--) {
```
Comment (hughrawlinson) [inline src/windowing.js:14]: Here is the important change, the rest is all formatting. Prettier strikes again!
